// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlite

import (
	"database/sql"
	"time"
)

type Asset struct {
	ID          string
	Type        sql.NullString
	Data        []byte
	Visibility  string
	MinimumCost int64
	LastUpdated sql.NullTime
}

type OauthToken struct {
	Token        string
	Provider     string
	AccessToken  string
	TokenType    string
	RefreshToken string
	ExpiresIn    time.Time
	Created      sql.NullTime
}

type Tier struct {
	ID          string
	Name        string
	Price       int64
	Description sql.NullString
}

type User struct {
	ID        string
	Name      string
	Email     sql.NullString
	Nickname  sql.NullString
	AvatarUrl sql.NullString
	JoinedAt  sql.NullTime
}

type UserTier struct {
	UserID         string
	TierID         sql.NullString
	Price          int64
	IsOneTime      bool
	IsCustomAmount bool
}
