// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlitec

import (
	"database/sql"
	"time"
)

type Asset struct {
	ID          string
	Data        []byte
	Filename    string
	Visibility  string
	MinimumCost int64
	LastUpdated sql.NullTime
	PreviewUrl  sql.NullString
	Width       int64
	Height      int64
}

type AssetRef struct {
	AssetID string
	PostID  sql.NullString
}

type OauthToken struct {
	Token        string
	Provider     string
	AccessToken  string
	TokenType    string
	RefreshToken string
	ExpiresIn    time.Time
	Created      time.Time
}

type Post struct {
	ID          string
	Data        []byte
	Visibility  string
	MinimumCost int64
	LastUpdated sql.NullTime
}

type Tier struct {
	ID          string
	Name        string
	Price       int64
	Description string
}

type User struct {
	ID         string
	Username   string
	Email      string
	RealName   string
	Pronouns   string
	AvatarUrl  string
	JoinedAt   time.Time
	IsOwner    bool
	UserConfig []byte
	SiteConfig []byte
}

type UserTier struct {
	UserID         string
	TierID         sql.NullString
	Price          int64
	IsOneTime      bool
	IsCustomAmount bool
	StartedAt      time.Time
	RenewedAt      time.Time
}
